file_format: "1"
id: yellow
name: Yellow
type: shield
url: https://github.com/MakotoKurauchi/helix
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - yellow_left
  - yellow_right
